
ignore:
    - rebuild.sh

siteEnvironment: prod

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      pageCategory: content page
      siteEnvironment: qa


