
exclude:
    - rebuild.sh
    - safe-listing.html

siteEnvironment: prod

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      pageCategory: content page
      siteEnvironment: qa


